/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aula;

public class App {    
    public static void main(String[] args) {        
        Pessoa p = new Pessoa();

    }
}
