/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

public class App {
    // App
    public static void main(String[] args) {
        if(args.length > 0){
            System.out.println(args[0]);
            System.out.println(args[1]);
        }
    }
}

// 576
// 5 nota(s) de R$ 100,00 
// 1 nota(s) de R$ 50,00 
// 1 nota(s) de R$ 20,00
// 0 nota(s) de R$ 10,00
// 1 nota(s) de R$ 5,00
// 0 nota(s) de R$ 2,00
// 1 nota(s) de R$ 1,00
